var Schema = require('mongoose').Schema;
var connection = require('../connector');

/*
roomid will be the mongodb-autogenerated _id field
*/
var RoomSchema = new Schema({
  course: String,
  professor: [String],
  TA_list: {type: [String], default: []},
  status: {type: String, default: 'inactive'},
  created_at: {type: Date, default: Date.now},
  students_in_room: {type: [String], default: []}
});

var RoomModel = connection.model('Room', RoomSchema);

module.exports = RoomModel;
